apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: go-pdhhcqsy
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-pdhhcqsy 
  name: go-pdhhcqsy
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: go-pdhhcqsy
    weight: 100 
