apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: go-pdhhcqsy-gitops
  description: This is GitOps manifest for go-pdhhcqsy   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=go-pdhhcqsy
    backstage.io/kubernetes-id: go-pdhhcqsy 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: go-pdhhcqsy
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:go-pdhhcqsy
